### ISSUE TITLE
Make news to get random entry like kiosk

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#346]
https://github.com/f-klubben/stregsystemet/blob/9748ebebecc7cdb8fca69457aad70fa1a86924a2/stregsystem/views.py#L55

Multiple news might want to be shown at same time, randomly pick upon load which one to show. 

Currently, if more than one exist for some timestamp, we get an error on ORM filter `.get()` which blocks stregsystemet from loading.

**Comment by krestenlaust** [comment]
Are there any news entries in the fixtures? Because I'm not sure where they are displayed exactly

**Comment by falkecarlsen** [comment]
No, I don't think so. You can load the most common fixture (the one with mobilepay), add some yourself and dump an updated fixture with: https://docs.djangoproject.com/en/4.2/ref/django-admin/#dumpdata

**Comment by krestenlaust** [comment]
> No, I don't think so. You can load the most common fixture (the one with mobilepay), add some yourself and dump an updated fixture with: https://docs.djangoproject.com/en/4.2/ref/django-admin/#dumpdata

I've been trying to dump my improved fixture, using multiple different systems, but to no avail.

'Command': `django-admin dumpdata`
`django.core.exceptions.ImproperlyConfigured: Requested setting TEMPLATES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing sett
ings.`

<details>
<summary>Full traceback</summary>
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\runpy.py", line 193, in _run_module_as_main                                              
    "__main__", mod_spec)                                                                                                                       
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\runpy.py", line 85, in _run_code                                                         
    exec(code, run_globals)                                                                                                                     
  File "C:\ProgramData\miniconda3\envs\stregsystem\Scripts\django-admin.exe\__main__.py", line 7, in <module>                                   
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()                                                                                                                           
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\management\__init__.py", line 375, in execute                  
    self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                     
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv                
    self.execute(*args, **cmd_options)                                                                                                          
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\core\checks\templates.py", line 29, in check_string_if_invalid_is_string
    for conf in settings.TEMPLATES:
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\ProgramData\miniconda3\envs\stregsystem\lib\site-packages\django\conf\__init__.py", line 64, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting TEMPLATES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing sett
ings.
</details>

I've been reading up on settings.py in django, but haven't been able to figure out what the issue is. How were the original fixtures dumped? (My setup: Clone -> Load fixture -> Modify in admin panel -> `django-admin dumpdata`)

**Comment by falkecarlsen** [comment]
@krestenlaust read the first two paragraphs of the docs I linked. Your issue is that DJANGO_SETTINGS_MODULE env is not set, as the error correctly says.
Second paragraph says that django-admin and manage.py are identical, but the latter sets this env var.

I only remember using manage.py for stregsystemet, you should probably too.
